<a href="https://colab.research.google.com/github/SergiySpv/ney_m22/blob/main/Lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Лабораторна №2

З дисципліни "Нейронні мережі"

Студентка групи КН-31

Сопова Сергія

створити набір даних із заданим розподілом (розподіл та розмір за власним рішенням), визначити його властивості (shape, rank, size, axis)

In [4]:

import tensorflow as tf
import numpy as np
import pandas as pd
data = np.random.uniform(0,10, size=(13, 13)).astype(int)
tensor = tf.convert_to_tensor(data)
print(tensor)

tf.Tensor(
[[6 3 6 3 5 3 1 9 5 4 8 2 3]
 [9 3 1 5 3 0 5 7 3 9 5 5 9]
 [8 8 1 5 4 0 0 8 7 5 3 6 7]
 [7 4 1 4 2 0 7 5 7 3 8 4 5]
 [0 5 2 4 7 6 4 2 3 5 5 8 6]
 [4 1 7 7 3 6 7 3 4 9 2 2 7]
 [1 7 5 1 1 1 0 1 7 5 7 2 0]
 [5 7 4 7 7 7 1 7 2 2 7 2 1]
 [0 0 5 8 0 5 3 0 8 8 4 2 4]
 [0 6 6 5 2 4 6 2 1 1 7 3 3]
 [4 3 7 2 6 0 7 2 5 8 3 8 8]
 [0 8 1 2 7 3 2 7 0 1 6 3 3]
 [0 5 1 5 0 6 3 5 2 1 4 1 0]], shape=(13, 13), dtype=int64)


Продемонструвати основні математичні операції над тензорами



In [7]:
custom_tensor = tf.ones(shape=(3, 4, 4))

print(custom_tensor)

# getting dim, shape, size

print(custom_tensor.shape)
print(custom_tensor.ndim)
print(tf.size(custom_tensor))
print(tf.rank(custom_tensor))

tf.expand_dims(custom_tensor, axis=-1)

tf.Tensor(
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]], shape=(3, 4, 4), dtype=float32)
(3, 4, 4)
3
tf.Tensor(48, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)


<tf.Tensor: shape=(3, 4, 4, 1), dtype=float32, numpy=
array([[[[1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.]]],


       [[[1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.]]],


       [[[1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.]]]], dtype=float32)>

Crud

In [8]:
tensor = tf.constant([[1, 2, 3],[4, 5, 6],[7, 8, 9],[10, 11, 12]])
print(tensor)
print(tf.reshape(tensor, shape=(1, 12)))

tf.Tensor(
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]], shape=(4, 3), dtype=int32)
tf.Tensor([[ 1  2  3  4  5  6  7  8  9 10 11 12]], shape=(1, 12), dtype=int32)
